version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  heroku: circleci/heroku@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          filters:
            branches:
              ignore: master
      - heroku/deploy-via-git
  earlymorning:
    triggers:
      - schedule:
          cron: "14 20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - maven/test
      - heroku/deploy-via-git:
          requires:
            - maven/test
