version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  heroku: circleci/heroku@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          filters:
            branches:
              ignore: master
      - heroku/deploy_via_git